---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: csns
  name: csapp-pvc
  labels:
    name: csapp-pvc
    app: cs
    tier: database
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: do-block-storage # This is default
  accessModes:
    - ReadWriteOnce
