---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggdb
      tier: database
  template:
    metadata:
      name: bggdb-pod
      labels:
        app: bggdb
        tier: database
    spec:
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: bggdb-pvc
        - name: config-vol 
          configMap:
            name: bgg-cm
        - name: tmp-vol
          emptyDir: {}
      containers:
        - name: bggdb-container
          image: stackupiss/bgg-database:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: data-vol
            mountPath: /var/lib/mysql
          - name: config-vol
            mountPath: /opt/config
          - name: tmp-vol
            mountPath: /opt/tmp
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
spec:
  type: ClusterIP
  selector:
    app: bggdb
    tier: database
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP