---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bggns
  name: bggdb-pvc
  labels:
    name: bggdb-pvc
    app: bgg
    tier: database
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: do-block-storage # This is default
  accessModes:
    - ReadWriteOnce
